"""ajout de cover big et de preview

Revision ID: b3e4e525a8ea
Revises: 17f0274e0e7d
Create Date: 2026-03-29 11:12:23.324442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e4e525a8ea'
down_revision = '17f0274e0e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_big', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('preview', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('preview')
        batch_op.drop_column('cover_big')

    # ### end Alembic commands ###
